DROP TABLE IF EXISTS songs;

CREATE TABLE songs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT UNIQUE NOT NULL,
  artist TEXT NOT NULL,
  duration INTEGER NOT NULL,
  uploadDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);